---
- name: Create VM vmware
  hosts: localhost
  gather_facts: no
  vars:
    server_size: "{{ lookup('file','../files/jsons/vmware{{ vm_size }}.json')|from_json }}"
  tasks:
    - name: Create a virtual machine on given ESXi hostname
      vmware_guest:
        hostname: "{{ vmware_host }}"
        username: VCENTER_USER
        password: VCENTER_PASSWORD
        datacenter: "{{ datacenter | default ('DEFAULT_DATACENTER)}}"
        cluster: "{{ cluster | default ('DEFAULT_CLUSTER') }}"
        validate_certs: no
        folder: /Ansible
        name: "{{ vm_name }}"
        #template: Template_Rhel7_base
        guest_id: rhel7_64Guest
        state: poweredon
        datastore: "{{ datastore | default ('HWAPPACP')}}"
        hardware:
          memory_mb: "{{ server_size.memory }}"
          num_cpus: "{{ server_size.cpu }}"
        cdrom:
            type: iso
            iso_path: "[NFS_ISO_INSTALL] new2.iso"
        networks:
        - name: "{{ vmdef.vlan }}"
          ip: "{{ vmdef.ip }}"
          netmask: "{{ vmdef.mask }}"
          gateway: "{{ vmdef.gateway }}"


 #   - Add oracle disks
